grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e1_SI-2.markDup_metrics.txt
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e1_SII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e1_SIII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e2_SI-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e2_SII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e2_SIII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e3_SI-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e3_SII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e3_SIII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e5_SI-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e5_SII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e5_SIII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e6_SI-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e6_SII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e9_SI-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e9_SII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e9_SIII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e13_SI-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e13_SII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e13_SIII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e14_SII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e14_SIII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e15_SI-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e15_SII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e16_SI-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e16_SII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e16_SIII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e17_SI-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e17_SII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e17_SIII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e19_SI-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e19_SII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e19_SIII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e20_SI-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e20_SII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e20_SIII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e21_SI-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e21_SII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e21_SIII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e22_SI-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e22_SII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e22_SIII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e23_SI-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e23_SII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e23_SIII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e24_SI-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e24_SII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e24_SIII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e25_SI-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e26_SI-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e26_SII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e26_SIII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e27_SI-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e27_SII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e27_SIII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e28_SI-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e28_SII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e28_SIII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e29_SI-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e29_SII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e29_SIII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e30_SI-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e30_SII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e31_SI-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e31_SII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e31_SIII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e32_SI-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e32_SII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e32_SIII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e33_SI-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e33_SII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e33_SIII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e34_SI-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e34_SII-2.markDup_metrics.txt | grep -v LIBRARY
grep -A1 LIBRARY /user01/group_folders/Personal/Ximena/SOMITES/somitogenesis2019/ATAC-seq/data/DUPSmetrics/e34_SIII-2.markDup_metrics.txt | grep -v LIBRARY
